name: sellerapp
description: "Best 3 Deals Seller app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  sqflite: 2.3.3+2
  http: ^1.3.0
  path: ^1.9.0
  geolocator: 12.0.0
  geocoding: ^3.0.0
  shared_preferences: 2.5.2
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
    - assets/placeholder.jpg
